GET http://localhost/gateway/openapi/hello-service/args

###

GET http://localhost/gateway/api/feign/args
X-AUTH-TOKEN: 05122:fecb777ad7244517a1d094aadaa11e1c

###

GET http://localhost/feign/args

###

GET http://localhost/hystrix/args

###
